### ISSUE TITLE
'deployStash' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Tim-91** [niiknow/vue-wp-plugin-starter#1]
First of all thank you for sharing this project! The ("npm run watch") preview works great, but when I try to create the vendor file via the "composer app:package" command I run into the following error message: 

deployStash=`git stash create`; git archive --worktree-attributes --format=zip -o dist.zip ${deployStash:-HEAD}
'deployStash' is not recognized as an internal or external command,
operable program or batch file.
Script deployStash=`git stash create`; git archive --worktree-attributes --format=zip -o dist.zip ${deployStash:-HEAD} handling the app:package event returned with error code 1

Do I miss something to run the "composer app:package" command?

**Comment by noogen** [comment]
Issue might be with shell command not compatible.  I've adjust the `git archive` command.  Let me know if that work.

**Comment by Tim-91** [comment]
Thanks for the quick response! I still get the following error message:

Script git archive --worktree-attributes --format=zip -o dist.zip $(git stash create) handling the app:package event returned with error code 1

The 'deployStash' is not recognized as an internal or external command part is now gone, but the line of code is still not being executed.

**Comment by noogen** [comment]
Can you execute `git archive --worktree-attributes --format=zip -o dist.zip $(git stash create)` to see and let me know what error you're getting?  What shell are you running in (bash, sh, tsh, etc...) or is it in windows command/batch?

I'm guessing you're in windows and cannot use `$()` for command substitution.  You might have to change it from to remove the `$` sign so it'll simply be `(git stash create)` instead.  Or switch to a unix shell in windows for a workaround.

Alternatively, we'll have to write nodejs tool to zip/package the app instead of using shell command.  I don't have time to work on it immedately but you're welcome to do a pull request.  It may take a week or so for me to get the nodejs script in to do this.

**Comment by noogen** [comment]
Try the latest `composer app:package` and let me know.  I've rewritten packaging to use nodejs archiver so it'll work with any system.

**Comment by Tim-91** [comment]
Works like a charm now! I don't receive any errors anymore when I run the "composer app:package" command. Also tested the plugin in Wordpress, the zip file also works. Thanks for your help!
