### ISSUE TITLE
importing image could not be found

### ISSUE THREAD

**Issue by gummy-byte** [niiknow/vue-wp-plugin-starter#2]
hello niiknow,
I'm a newbie in developing wordpress plugin. I've already finish building my vue project via and now integrating my vue application with your skeleton plugin. I could see the that you compile all css and  js file is compile into public folder **including the image file** 
but when i try to put the image src like `src='@public/image/image.png'`, the path seems could not be resolve by the browser.
May I know if there anything I could do to import image into my component?

Things I have tried
1. import image as object in script and reference it in the component. but it could resolve the module.
2. use usual import image from vue component such as `src='./assets/img/image.png'`. Browser will resolve this as `wordpress.test/assets/img/image.png`

**Comment by noogen** [comment]
You have to realize that this is a plugin.  Therefore, the path should be relative to the plugin directory, which should be something like `wordpress.test/wp-content/plugins/your-plugin-name/public/image/image.png`.

So instead of mapping it directly, I would suggest doing something like `:src="getPluginPath() + 'public/image/image.png'"` and create your own `getPluginPath` method on the component to resolve the plugin path to `/` in development and `/wp-content/plugins/your-plugin-name` in production.

MY FUTURE TODO: If time allow, I'm considering adding this feature as a vue mixin to the example app.

**Comment by gummy-byte** [comment]
> You have to realize that this is a plugin. Therefore, the path should be relative to the plugin directory, which should be something like `wordpress.test/wp-content/plugins/your-plugin-name/public/image/image.png`.
> 
> So instead of mapping it directly, I would suggest doing something like `:src="getPluginPath() + 'public/image/image.png'"` and create your own `getPluginPath` method on the component to resolve the plugin path to `/` in development and `/wp-content/plugins/your-plugin-name` in production.
> 
> MY FUTURE TODO: If time allow, I'm considering adding this feature as a vue mixin to the example app.

**Comment by noogen** [comment]
@gummy-byte I had time so I add the `getPluginUrl` method.  See usage here: https://github.com/niiknow/vue-wp-plugin-starter/blob/main/src/frontend/views/Home.vue#L5
